import { describe, expect, it } from "vitest"

import {
  resolveDnsConfig,
  resolveDnsConfigSource,
} from "../services/preview-worker/gvisor/dnsConfig"

function fakeReadFile(files: Record<string, string>) {
  return (path: string): string | null => files[path] ?? null
}

describe("resolveDnsConfigSource", () => {
  it("keeps /etc/resolv.conf when it already has a real, non-loopback nameserver (e.g. WSL2)", () => {
    const source = resolveDnsConfigSource({
      readFile: fakeReadFile({
        "/etc/resolv.conf": "nameserver 10.255.255.254\n",
      }),
    })

    expect(source).toBe("/etc/resolv.conf")
  })

  it("falls back to the systemd-resolved uplink file when /etc/resolv.conf is the loopback stub", () => {
    const source = resolveDnsConfigSource({
      readFile: fakeReadFile({
        "/etc/resolv.conf": "nameserver 127.0.0.53\noptions edns0 trust-ad\n",
        "/run/systemd/resolve/resolv.conf": "nameserver 172.31.0.2\n",
      }),
    })

    expect(source).toBe("/run/systemd/resolve/resolv.conf")
  })

  it("treats the IPv6 loopback address as unusable too", () => {
    const source = resolveDnsConfigSource({
      readFile: fakeReadFile({
        "/etc/resolv.conf": "nameserver ::1\n",
        "/run/systemd/resolve/resolv.conf": "nameserver 172.31.0.2\n",
      }),
    })

    expect(source).toBe("/run/systemd/resolve/resolv.conf")
  })

  it("falls back to /etc/resolv.conf if neither file has a usable nameserver", () => {
    const source = resolveDnsConfigSource({
      readFile: fakeReadFile({
        "/etc/resolv.conf": "nameserver 127.0.0.53\n",
        "/run/systemd/resolve/resolv.conf": "nameserver 127.0.0.1\n",
      }),
    })

    expect(source).toBe("/etc/resolv.conf")
  })

  it("falls back to /etc/resolv.conf if neither file exists", () => {
    const source = resolveDnsConfigSource({ readFile: fakeReadFile({}) })

    expect(source).toBe("/etc/resolv.conf")
  })

  it("falls back to /etc/resolv.conf if it is missing but has no usable uplink either", () => {
    const source = resolveDnsConfigSource({
      readFile: fakeReadFile({
        "/run/systemd/resolve/resolv.conf": "nameserver 127.0.0.1\n",
      }),
    })

    expect(source).toBe("/etc/resolv.conf")
  })

  it("uses the uplink file when /etc/resolv.conf is missing entirely but the uplink is usable", () => {
    const source = resolveDnsConfigSource({
      readFile: fakeReadFile({
        "/run/systemd/resolve/resolv.conf": "nameserver 172.31.0.2\n",
      }),
    })

    expect(source).toBe("/run/systemd/resolve/resolv.conf")
  })

  it("ignores malformed/comment lines and still finds a real nameserver", () => {
    const source = resolveDnsConfigSource({
      readFile: fakeReadFile({
        "/etc/resolv.conf":
          "# generated by NetworkManager\nsearch example.com\nnameserver 8.8.8.8\n",
      }),
    })

    expect(source).toBe("/etc/resolv.conf")
  })

  it("returns the exact canonical IPv4 resolver addresses used by firewall exceptions", () => {
    const config = resolveDnsConfig({
      readFile: fakeReadFile({
        "/etc/resolv.conf": [
          "nameserver 172.31.0.2",
          "nameserver 169.254.169.253",
          "nameserver 172.31.0.2",
          "nameserver 8.8.8.999",
          "nameserver ::1",
        ].join("\n"),
      }),
    })

    expect(config).toEqual({
      source: "/etc/resolv.conf",
      nameservers: ["172.31.0.2", "169.254.169.253"],
    })
  })

  it("does not expose loopback, malformed, multicast, or IPv6 resolvers to the IPv4-only sandbox", () => {
    const config = resolveDnsConfig({
      readFile: fakeReadFile({
        "/etc/resolv.conf": [
          "nameserver 127.0.0.53",
          "nameserver 0.0.0.0",
          "nameserver 224.0.0.1",
          "nameserver fd00:ec2::253",
          "nameserver text.invalid",
        ].join("\n"),
      }),
    })

    expect(config).toEqual({ source: "/etc/resolv.conf", nameservers: [] })
  })
})
