import { describe, expect, it } from "vitest"

import {
  createPostgresScramSha256Verifier,
  validatePostgresScramSha256Verifier,
} from "../core/backendDatabase/scramVerifier"

describe("PostgreSQL SCRAM-SHA-256 verifier", () => {
  it("matches the RFC 7677 password/salt/iteration known-answer inputs", () => {
    // Expected value was independently established from RFC 7677's
    // password `pencil`, salt, and iteration-count example, not generated by
    // the helper under test.
    expect(
      createPostgresScramSha256Verifier(
        "pencil",
        Buffer.from("W22ZaJ0SNY7soEsUEjb6gQ==", "base64"),
        4096,
      ),
    ).toBe(
      "SCRAM-SHA-256$4096:W22ZaJ0SNY7soEsUEjb6gQ==$WG5d8oPm3OtcPnkdi4Uo7BkeZkBFzpcXkuLmtbsT4qY=:wfPLwcE6nTWhTAmQ7tl2KeoiWGPlZqQxSrmfPwDl2dU=",
    )
  })

  it.each([0, -1, 1.5, Number.NaN, Number.POSITIVE_INFINITY])(
    "rejects invalid iteration count %s",
    (iterations) => {
      expect(() =>
        createPostgresScramSha256Verifier(
          "safe_password",
          new Uint8Array([1]),
          iterations,
        ),
      ).toThrow(/positive integer/)
    },
  )

  it("rejects empty salt and passwords outside Peephole's generator grammar", () => {
    expect(() =>
      createPostgresScramSha256Verifier(
        "safe_password",
        new Uint8Array(),
        4096,
      ),
    ).toThrow(/salt/)
    expect(() =>
      createPostgresScramSha256Verifier(
        "not arbitrary unicode 🐘",
        new Uint8Array([1]),
        4096,
      ),
    ).toThrow(/safe ASCII/)
  })

  it("rejects malformed, non-canonical, and wrong-length verifier parts", () => {
    for (const value of [
      "SCRAM-SHA-256$4096:AA==$AA==:AA==",
      "SCRAM-SHA-256$0:YWJj$YWJj:YWJj",
      "SCRAM-SHA-256$4096:not_base64$YWJj:YWJj",
      "md5deadbeef",
    ]) {
      expect(() => validatePostgresScramSha256Verifier(value)).toThrow(
        /verifier is invalid/,
      )
    }
  })
})
